/*
 * Lunch Orders
 *
 * This API allows lunch ordering.
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package orderItems

import (
	"github.com/cyberjacob/LunchOrders-Api/models/order"
	"github.com/cuvva/ksuid"
)

type OrderItems struct {
	Id       ksuid.ID `json:"id,omitempty" gorm:"type:blob"`
	Item     string   `json:"item,omitempty"`
	Quantity float32  `json:"quantity,omitempty"`
	Cost     float32  `json:"cost,omitempty"`

	Order      Order    `gorm:"foreignkey:SessionRefer"` // use UserRefer as foreign key
	OrderRefer ksuid.ID `gorm:"type:blob"`
}
