/*
 * Lunch Orders
 *
 * This API allows lunch ordering.
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package api

import (
	"github.com/cyberjacob/LunchOrders-Api/api/v1/order"
	"github.com/cyberjacob/LunchOrders-Api/api/v1/session"
	"github.com/gin-contrib/cors"
	"github.com/gin-gonic/gin"
	"net/http"
)

type Route struct {
	Name        string
	Method      string
	Pattern     string
	HandlerFunc http.HandlerFunc
}

type Routes []Route

func NewRouter() *gin.Engine {
	router := gin.Default()

	corsConfig := cors.DefaultConfig()
	corsConfig.AllowOrigins = []string{"http://localhost:8456", "http://localhost"}

	router.Use(cors.New(corsConfig))

	router.Static("/swaggerui/", "./swagger-ui")

	v1Group := router.Group("api/v1")
	{
		v1Group.StaticFile("/swagger.yml", "api/v1/swagger.yml")
		order.SetupOrderRoutes(v1Group.Group("/order"))
		session.SetupSessionRoutes(v1Group.Group("session"))
	}

	return router
}
